### ISSUE TITLE
[BUG] 안 푼 날짜 오류

### ISSUE THREAD

**Issue by heehoh** [0D0S/odos#3]
<img width="469" alt="Screen Shot 2023-11-18 at 9 30 43 PM" src="https://github.com/0D0S/odos/assets/114281631/399f222c-1497-44ec-91b1-8e7fcf599b3a">

<img width="481" alt="Screen Shot 2023-11-18 at 9 30 53 PM" src="https://github.com/0D0S/odos/assets/114281631/757913eb-759f-48cf-93e6-c24be04b3232">

- 하루가 안 지났는데 안푼 날짜가 -2일이었는데 -3일로 바뀜 😡

**Comment by kdelphinus** [comment]
데이터 롤백했습니다
