### ISSUE TITLE
[BUG] 푼 사람 체크 오류

### ISSUE THREAD

**Issue by hyobb109** [0D0S/odos#4]
풀었는데 안 푼 사람으로 나옴!!

![image](https://github.com/0D0S/odos/assets/105159293/c3c733bb-5076-4bdd-ab7e-d5cb6d8531ae)
![image](https://github.com/0D0S/odos/assets/105159293/fdd9acc6-f327-4d8d-8afa-cc84032c572a)

**Comment by kdelphinus** [comment]
![스크린샷 2023-11-19 22-25-02](https://github.com/0D0S/odos/assets/68101516/c92b3a30-e9a6-4ca5-a0c8-fb7a7155f83f)
![스크린샷 2023-11-19 22-24-50](https://github.com/0D0S/odos/assets/68101516/e3378fd3-ec6a-40d1-bc00-b858593d3298)

새벽 0시에 풀고 다음날 13시에 푸셨는데 백준 문제에 맞춰서 새벽 6시에 리셋이 되기 때문에 0시에 푼거는 다음날 적용 안 되고 전날 푼 걸로 처리됩니다.

밑에 공지에 6시에 시작된다고 명시해놓을게요.
